name: four_brothers
description: Four Brothers Sports Center Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  share_plus: ^12.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/products/
    - assets/products/Mercurial1.JPEG
    - assets/products/Mercurial2.JPEG
    - assets/products/Nike1.JPEG
    - assets/products/Nike2.JPEG
    - assets/products/AirZoom.JPEG

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"